name: Keep API Alive

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  keep_api_awake:
    runs-on: ubuntu-latest
    steps:
    - name: Ping API to keep it awake
      run: curl https://attendance-system-45w9.onrender.com/
